### ISSUE TITLE
Couldn't run test_tracktor.py

### ISSUE THREAD

**Issue by sudomaze** [phil-bergmann/tracking_wo_bnw#133]
I have installed the packages per README and I downloaded MOT dataset. I couldn't run test_tracktor.py. Here is the error that I got:

```
INFO - main - Initializing object detector(s).
INFO - main - Initializing reID network(s).
ERROR - test_tracktor - Failed after 0:00:11!
Traceback (most recent calls WITHOUT Sacred internals):
  File "experiments/scripts/test_tracktor.py", line 120, in main
    reid_network = ReIDNetwork_resnet50(pretrained=False, **reid_cfg["model_args"])
KeyError: 'model_args'
```

Thanks!

**Comment by timmeinhardt** [comment]
Did u download the pre-trained model files? Including the Faster R-CNN and reID model files?

**Comment by sudomaze** [comment]
Yes, I did. I have downloaded the pre-trained model files and moved them to the output folder:

```
├── faster_rcnn_fpn
│   ├── faster_rcnn_fpn_training_mot_17
│   │   ├── model_epoch_27.model
│   │   ├── MOT17-01.txt
│   │   ├── MOT17-02.txt
│   │   ├── ...
│   │   └── MOT17-14.txt
│   ├── faster_rcnn_fpn_training_mot_17_split_09
│   ├── faster_rcnn_fpn_training_mot_20
│   │   ├── model_epoch_27.model
│   │   ├── MOT20-01.txt
│   │   ├── MOT20-02.txt
│   │   ├── ...
│   │   └── MOT20-08.txt
│   └── faster_rcnn_fpn_training_mot_20_split_05
│       └── MOT20-05.txt
├── faster_rcnn_fpn_training_mot_17
│   ├── model_epoch_27.model
│   ├── MOT17-01.txt
│   ├── MOT17-02.txt
│   ├── ...
│   └── MOT17-14.txt
├── faster_rcnn_fpn_training_mot_20
│   ├── model_epoch_27.model
│   ├── MOT20-01.txt
│   ├── MOT20-02.txt
│   ├── ...
│   └── MOT20-08.txt
└── tracktor
    ├── MOT17
    │   └── Tracktor++
    │       ├── MOT17-01-DPM.txt
    │       ├── MOT17-01-FRCNN.txt
    │       ├── MOT17-01-SDP.txt
    │       ├── MOT17-02-DPM.txt
    │       ├── MOT17-02-FRCNN.txt
    │       ├── MOT17-02-SDP.txt
    │       ├── ...
    │       ├── MOT17-14-DPM.txt
    │       ├── MOT17-14-FRCNN.txt
    │       ├── MOT17-14-SDP.txt
    │       └── sacred_config.yaml
    ├── MOT20
    │   └── Tracktor++
    │       ├── MOT20-01.txt
    │       ├── MOT20-02.txt
    │       ├── ...
    │       └── MOT20-08.txt
    └── reid
        └── res50-mot17-batch_hard
            ├── ResNet_iter_25245.pth
            └── sacred_config.yaml
```

**Comment by timmeinhardt** [comment]
Does the `tracktor/reid/res50-mot17-batch_hard/sacred_config.yaml` include the `model_args` field? And did you pull the latest version of the code and download the most recent models files (`tracking_wo_bnw-output_v4.zip`).

**Comment by sudomaze** [comment]
Yes. I did and I think I have pulled the latest version with tracking_wo_bnw-output_v4.zip.

```yaml
reid:
  cnn:
    output_dim: 128
  dataloader:
    K: 4
    P: 18
    crop_H: 256
    crop_W: 128
    max_per_person: 1000
    normalize_mean:
    - 0.485
    - 0.456
    - 0.406
    normalize_std:
    - 0.229
    - 0.224
    - 0.225
    transform: random
    vis_threshold: 0.3
  db_train: train
  db_val: false
  desription: all
  lr_scheduler: true
  max_epochs: 69
  model_args:
    loss: batch_hard
    margin: 0.2
    prec_at_k: 3
  module_name: reid
  name: res50-mot17-batch_hard
  seed: 12345
  solver:
    optim: Adam
    optim_args:
      lr: 0.0003
      weight_decay: 0.0
seed: 453695
```

I will nuke the folder and do it again to ensure that my setup is right, then I will update you.
